---
- hosts: webservers
  vars:
    install_path: "~" # we'll move it to /srv once we set up a new user and group in this script
    folder_name: Waterspout
    virtualenv_folder_name: venv_waterspout
    python_version: 3.8
    python_executable: "python{{ python_version }}"
    pip_executable: "pip{{ python_version }}"
  tasks:
    - name: Configure firewall to deny incoming traffic by default
      become: true
      become_method: sudo
      ufw:
        direction: incoming
        default: deny
    - name: Allow and limit SSH
      become: true
      become_method: sudo
      ufw:
        rule: limit
        port: ssh
        proto: tcp
    - name: Allow Port 80
      become: true
      become_method: sudo
      ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Allow Port 443 (SSL/TLS)
      become: true
      become_method: sudo
      ufw:
        rule: allow
        port: '443'
        proto: tcp
    - name: Enable firewall
      become: true
      become_method: sudo
      ufw:
        state: enabled

    # we don't update afterward because we still need to add the key before we can
    - name: Add Ubuntu GIS PPA so we can get GDAL in next step
      become: true
      become_method: sudo
      apt_repository:
        repo: ppa:ubuntugis/ppa
        update_cache: no

    - name: Add Ubuntu GIS PPA Key
      become: true
      become_method: sudo
      apt_key:
        id: 314DF160

      # install some basic packages we'll want for this project
    - name: Install system apt packages
      become: true
      become_method: sudo
      apt:
        update_cache: yes
        name: ['git','nginx-full','{{ python_executable }}','{{ python_executable }}-dev','python3-pip','virtualenv','postgresql','gdal-bin','libgdal-dev']
        state: present
      # not sure if the python-pip here will install it for python 3.8 - I'm not sure it will based on experience
      # we may need to adjust how we get pip

    - name: Get installed GDAL version so we can install corresponding version in Python
      command: "gdalinfo --version"
      register: gdal_version_text

    - name: Installed GDAL Version Full Text
      debug:
        msg: "GDAL Version Detected: {{ gdal_version_text.stdout }}"

    # parse the gdal version reported to get the numeric representation for Python
    - name: Parse GDAL Version
      set_fact:
        gdal_version: "{{ gdal_version_text.stdout | regex_search('GDAL\\s(.*?),.*', '\\1') }}"

    - name: Installed GDAL Version
      debug:
        msg: "GDAL Version Detected: {{ gdal_version[0] }}"

    # need to verify that it's not going to make a folder /srv/Waterspout/Waterspout with this
    - name: Clone Waterspout to machine
      git:
        clone: yes
        repo: https://github.com/Water-Systems-Management-UCM/Waterspout
        dest: "{{ install_path }}/{{ folder_name }}"

    - name: Make virtualenv and install Python GDAL before rest of requirements (so it's present and matches correct version)
      pip:
        virtualenv: "{{ install_path }}/{{ virtualenv_folder_name }}/"
        virtualenv_python: "{{ python_executable }}"
        virtualenv_site_packages: no
        name: "GDAL"
        version: "{{ gdal_version[0] }}"

    - name: Install Python requirements
      pip:
        chdir: "{{ install_path }}"
        virtualenv: "{{ install_path }}/{{ virtualenv_folder_name }}/"
        requirements: "{{ install_path }}/{{ folder_name }}/requirements.txt"

    # TODO: Somewhere up above, configure GDAL
    # TODO: copy and reconfigure local settings
    #     Can we generate and configure postgres user accounts and store them in variables
    #     to plug into local settings files? Do I need a separate script that dumps local_settings files?
    #     or can I do a replacement of a template string with ansible?
    # TODO: Create user account for application to run as
    # TODO: Set permissions on application srv directory
    # TODO: Configure service for application
    # TODO: Run migrations
    # TODO: Process static files
    # TODO: Configure nginx reverse proxying
    # TODO: Fail2ban and other services
    # TODO: Move SSH port?
    # TODO: Check groundwater site setup instructions for other things that go here
    # TODO: Make application update playbook