---
- hosts: webservers
  vars:
    install_path: /srv
    folder_name: Waterspout
    virtualenv_folder_name: venv_waterspout
    python_executable: python3.8
  tasks:
    - name: Configure firewall
        ufw:
          direction: in
          default: deny
    - name: Allow and limit SSH
        ufw:
          rule: limit
          port: ssh
          proto: tcp
    - name: Allow Port 80
        ufw:
          rule: allow
          port: 80
          proto: tcp
    - name: Allow Port 443 (SSL/TLS)
        ufw:
          rule: allow
          port: 443
          proto: tcp
    - name: Enable firewall
        ufw:
          state: enabled

      # install some basic packages we'll want for this project
    - name: Install system apt packages
        become: true
        become_method: sudo
        apt: update_cache=yes name={{ item }} state=present
        # not sure if the python-pip here will install it for python 3.8 - I'm not sure it will based on experience
        # we may need to adjust how we get pip
        with_items:
          - git
          - nginx-full
          - python3.8
          - python3.8-dev
          - python-pip
          - software-properties-common
          - python-software-properties
          - postgresql

    # need to verify that it's not going to make a folder /srv/Waterspout/Waterspout with this
    - name: Clone Waterspout to machine
        git:
          clone: yes
          repo: https://github.com/Water-Systems-Management-UCM/Waterspout
          dest: {{ install_path }}/{{ folder_name }}

    # make sure Python has virtualenv installed
    - name: Configure Python - Install virtualenv
        pip:
          name: virtualenv
          executable: {{ python_executable }}
    - name: Install Python requirements
        pip:
          chdir: {{ install_path }}
          virtualenv: {{ install_path }}/{{ virtualenv_folder_name }}/
          virtualenv_python: {{ python_executable }}
          virtualenv_site_packages: no
          requirements: {{ install_path }}/{{ folder_name }}/requirements.txt