# Generated by Django 3.0.6 on 2020-06-04 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crop_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_id', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=100)),
                ('geometry', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_id', models.CharField(max_length=100)),
                ('geometry', models.TextField(blank=True, null=True)),
                ('model_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.ModelArea')),
            ],
        ),
        migrations.CreateModel(
            name='RegionExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(max_length=5)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_attributes', to='waterspout_api.Region')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.RegionGroup'),
        ),
        migrations.AddField(
            model_name='region',
            name='model_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.ModelArea'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('status_message', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('result_values', models.TextField(blank=True, default='', null=True)),
                ('log_data', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('calibrated_parameters', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='waterspout_api.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='modelarea',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='waterspout_api.Organization'),
        ),
        migrations.CreateModel(
            name='CropGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crops', models.ManyToManyField(to='waterspout_api.Crop')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.Organization'),
        ),
        migrations.CreateModel(
            name='CalibrationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.TextField()),
                ('model_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.ModelArea')),
            ],
        ),
        migrations.CreateModel(
            name='CalibratedParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.CalibrationSet')),
            ],
        ),
        migrations.CreateModel(
            name='RegionModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_proportion', models.FloatField()),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='waterspout_api.ModelRun')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifications', to='waterspout_api.Region')),
            ],
            options={
                'unique_together': {('model_run', 'region')},
            },
        ),
    ]
