# Generated by Django 3.1 on 2020-08-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibratedparameter',
            old_name='i',
            new_name='crop',
        ),
        migrations.RenameField(
            model_name='calibratedparameter',
            old_name='g',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='i',
            new_name='crop',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='g',
            new_name='region',
        ),
    ]
