# Generated by Django 3.1 on 2020-11-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelarea',
            name='map_center_latitude',
            field=models.DecimalField(decimal_places=2, default=38.1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelarea',
            name='map_center_longitude',
            field=models.DecimalField(decimal_places=2, default=-121.5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelarea',
            name='map_default_zoom',
            field=models.SmallIntegerField(default=9),
            preserve_default=False,
        ),
    ]
