# Generated by Django 3.1 on 2020-11-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='infeasbilities_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calibratedparameter',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.crop'),
        ),
        migrations.AlterField(
            model_name='calibratedparameter',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.region'),
        ),
        migrations.AlterField(
            model_name='modelarea',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waterspout_api.organization'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regiongroup',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.crop'),
        ),
        migrations.AlterField(
            model_name='result',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.region'),
        ),
        migrations.CreateModel(
            name='Infeasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('model_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infeasibilities', to='waterspout_api.modelrun')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infeasibilities', to='waterspout_api.region')),
            ],
        ),
    ]
