# Generated by Django 3.0.6 on 2020-07-15 22:31

from django.db import migrations, models
import django.db.models.deletion
import waterspout_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='calibrated_parameters_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='geometry',
            field=waterspout_api.models.SimpleJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regiongroup',
            name='geometry',
            field=waterspout_api.models.SimpleJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regionmodification',
            name='land_proportion',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name='regionmodification',
            name='model_run',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region_modifications', to='waterspout_api.ModelRun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regionmodification',
            name='water_proportion',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
