# Generated by Django 3.1 on 2020-11-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0002_auto_20201109_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelrun',
            old_name='infeasbilities_text',
            new_name='infeasibilities_text',
        ),
    ]
