# Generated by Django 3.1 on 2020-12-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0002_auto_20201125_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelarea',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_areas', to='waterspout_api.organization'),
        ),
        migrations.AlterField(
            model_name='region',
            name='internal_id',
            field=models.CharField(max_length=100),
        ),
    ]
