# Generated by Django 3.1 on 2020-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0003_auto_20201201_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelarea',
            name='max_crop_area',
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='max_land',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='max_price',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='max_water',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='max_yield',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='min_crop_area',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='min_land',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='min_price',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='min_water',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='modelarea',
            name='min_yield',
            field=models.PositiveSmallIntegerField(default=80),
        ),
    ]
