# Generated by Django 3.1 on 2020-11-10 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0003_auto_20201109_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='results',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_run', to='waterspout_api.resultset'),
        ),
        migrations.AlterField(
            model_name='result',
            name='gross_revenue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='net_revenue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='water_per_acre',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True),
        ),
    ]
