# Generated by Django 3.1 on 2020-10-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0004_auto_20201007_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='base_model_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='waterspout_api.modelrun'),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
