# Generated by Django 3.1 on 2020-11-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0004_auto_20201109_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infeasibility',
            name='model_run',
        ),
        migrations.RemoveField(
            model_name='modelrun',
            name='infeasibilities_text',
        ),
        migrations.AddField(
            model_name='infeasibility',
            name='result_set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='infeasibilities', to='waterspout_api.resultset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultset',
            name='infeasibilities_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
