# Generated by Django 3.1 on 2020-10-15 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0005_auto_20201008_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmodification',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifications', to='waterspout_api.crop'),
        ),
    ]
