# Generated by Django 3.1 on 2020-11-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0005_auto_20201110_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibratedparameter',
            name='resource_flag',
        ),
        migrations.RemoveField(
            model_name='calibratedparameter',
            name='xdiffland',
        ),
        migrations.RemoveField(
            model_name='calibratedparameter',
            name='xdifftotalland',
        ),
        migrations.RemoveField(
            model_name='calibratedparameter',
            name='xdiffwater',
        ),
        migrations.RemoveField(
            model_name='calibratedparameter',
            name='xlandsc',
        ),
        migrations.RemoveField(
            model_name='calibratedparameter',
            name='xwatersc',
        ),
        migrations.RemoveField(
            model_name='result',
            name='betalabor',
        ),
        migrations.RemoveField(
            model_name='result',
            name='betaland',
        ),
        migrations.RemoveField(
            model_name='result',
            name='betasupply',
        ),
        migrations.RemoveField(
            model_name='result',
            name='betawater',
        ),
        migrations.RemoveField(
            model_name='result',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='result',
            name='gamma',
        ),
        migrations.RemoveField(
            model_name='result',
            name='pimarginal',
        ),
        migrations.RemoveField(
            model_name='result',
            name='rho',
        ),
        migrations.RemoveField(
            model_name='result',
            name='sigma',
        ),
        migrations.RemoveField(
            model_name='result',
            name='tau',
        ),
        migrations.RemoveField(
            model_name='result',
            name='theta',
        ),
        migrations.CreateModel(
            name='InputDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.TextField()),
                ('model_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_data', to='waterspout_api.modelarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputDataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('omegaland', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegasupply', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegalabor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegaestablish', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegacash', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omeganoncash', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegatotal', models.DecimalField(decimal_places=1, max_digits=10)),
                ('xwater', models.DecimalField(decimal_places=10, max_digits=18)),
                ('p', models.DecimalField(decimal_places=10, max_digits=18)),
                ('y', models.DecimalField(decimal_places=5, max_digits=13)),
                ('xland', models.DecimalField(decimal_places=10, max_digits=18)),
                ('omegawater', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.crop')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_data_set', to='waterspout_api.inputdataset')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
