# Generated by Django 3.1 on 2020-10-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0006_auto_20201015_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='net_revenue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropmodification',
            name='price_proportion',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name='cropmodification',
            name='yield_proportion',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
