# Generated by Django 3.1 on 2021-03-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0007_auto_20201215_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibratedparameter',
            name='price_yield_correction_factor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='cropmodification',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crop_modifications', to='waterspout_api.crop'),
        ),
    ]
