# Generated by Django 3.1 on 2020-10-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0007_auto_20201026_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='net_revenue',
            field=models.DecimalField(decimal_places=3, max_digits=18, null=True),
        ),
    ]
