# Generated by Django 3.1 on 2021-03-02 21:33 UTC
# Written by Nick that same day


from django.db import migrations, models

from waterspout_api.support import load_price_yield_correction

def populate_price_yield_correction(apps, schema_editor):
    # load the calibration data as a CSV, then iterate through it and update the corresponding records in the DB

    # so, first, we need to look up all the calibration sets
    # and then check where their data came from

    # get the CalibrationSet object as the code/version existed at this point in the migration history
    # see https://docs.djangoproject.com/en/3.1/topics/migrations/
    CalibrationSet = apps.get_model('waterspout_api', "CalibrationSet")
    CalibratedParameter = apps.get_model('waterspout_api', "CalibratedParameter")

    load_price_yield_correction(CalibrationSet, CalibratedParameter)

class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0008_auto_20210302_1333'),
    ]

    operations = [
        migrations.AddField(  # first we need to add the field to modelarea that specifies the folder to load from
            model_name='modelarea',
            name='data_folder',
            field=models.CharField(max_length=255, default="dap"),
        ),
        migrations.RunPython(populate_price_yield_correction)
    ]
