# Generated by Django 3.1 on 2020-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0008_auto_20201026_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='gross_revenue',
            field=models.DecimalField(decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='water_per_acre',
            field=models.DecimalField(decimal_places=3, max_digits=18, null=True),
        ),
    ]
