# Generated by Django 3.1 on 2020-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0009_auto_20201027_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='water_per_acre',
            field=models.DecimalField(decimal_places=5, max_digits=18, null=True),
        ),
    ]
