# Generated by Django 3.1 on 2021-03-16 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0010_resultset_in_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultset',
            name='date_run',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='resultset',
            name='model_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='waterspout_api.modelrun'),
        ),
    ]
