# Generated by Django 3.1 on 2020-10-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0010_auto_20201027_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultset',
            name='dapper_version',
            field=models.CharField(default='2020.10.27', max_length=20),
            preserve_default=False,
        ),
    ]
