# Generated by Django 3.1 on 2020-11-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0011_resultset_dapper_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='model_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.modelarea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationset',
            name='model_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_data', to='waterspout_api.modelarea'),
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('crop_code', 'model_area')},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='organization',
        ),
    ]
