# Generated by Django 3.2 on 2021-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0015_modelareapreferences_lock_price_yield_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='include_net_revenue',
            field=models.BooleanField(default=False),
        ),
    ]
