# Generated by Django 3.2 on 2021-04-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0017_modelareapreferences_region_linked_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_model_run_creation_code_view',
            field=models.BooleanField(default=False),
        ),
    ]
