# Generated by Django 3.2 on 2021-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0018_modelareapreferences_allow_model_run_creation_code_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_viz_multiple_comparisons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_viz_normalization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_viz_worst_case',
            field=models.BooleanField(default=False),
        ),
    ]
