# Generated by Django 3.2 on 2021-04-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0019_auto_20210420_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelarea',
            name='feature_package_name',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
