# Generated by Django 3.2 on 2021-04-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0020_modelarea_feature_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_viz_region_filter',
            field=models.BooleanField(default=False),
        ),
    ]
