# Generated by Django 3.2 on 2021-04-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0021_modelareapreferences_allow_viz_region_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_removed_regions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_static_regions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='supports_irrigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='region',
            name='supports_rainfall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regionmodification',
            name='hold_static',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regionmodification',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
