# Generated by Django 3.2 on 2021-04-28 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0023_regionmultipliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodification',
            name='rainfall_proportion',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.CreateModel(
            name='RainfallSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.TextField()),
                ('model_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_data', to='waterspout_api.modelarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RainfallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_y', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('gross_revenue', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_results', to='waterspout_api.crop')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_resuls', to='waterspout_api.region')),
                ('result_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_result_set', to='waterspout_api.resultset')),
            ],
        ),
        migrations.CreateModel(
            name='RainfallParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('omegaland', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegasupply', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegalabor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('omegaestablish', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('omegacash', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('omeganoncash', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('omegatotal', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('xwater', models.DecimalField(decimal_places=10, max_digits=18)),
                ('p', models.DecimalField(decimal_places=10, max_digits=18)),
                ('y', models.DecimalField(decimal_places=5, max_digits=13)),
                ('xland', models.DecimalField(decimal_places=10, max_digits=18)),
                ('coef_intercept', models.DecimalField(decimal_places=5, max_digits=10)),
                ('coef_tsum', models.DecimalField(decimal_places=5, max_digits=10)),
                ('coef_tspr', models.DecimalField(decimal_places=5, max_digits=10)),
                ('coef_twin', models.DecimalField(decimal_places=5, max_digits=10)),
                ('coef_pespr', models.DecimalField(decimal_places=5, max_digits=10)),
                ('coef_pewin', models.DecimalField(decimal_places=5, max_digits=10)),
                ('coef_pesum', models.DecimalField(decimal_places=5, max_digits=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.crop')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterspout_api.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='rainfallparameter',
            index=models.Index(fields=['year'], name='waterspout__year_e37c47_idx'),
        ),
    ]
