# Generated by Django 3.2 on 2021-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0024_auto_20210428_1254'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['model_area_id', 'supports_rainfall'], name='waterspout__model_a_bbac95_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['model_area_id', 'supports_irrigation'], name='waterspout__model_a_3816c8_idx'),
        ),
    ]
