# Generated by Django 3.2 on 2021-04-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0026_auto_20210428_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfallparameter',
            name='rainfall_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_set', to='waterspout_api.rainfallset'),
            preserve_default=False,
        ),
    ]
