# Generated by Django 3.2 on 2021-04-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0027_rainfallparameter_rainfall_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfallparameter',
            name='xwater',
        ),
        migrations.RemoveField(
            model_name='result',
            name='xwater',
        ),
    ]
