# Generated by Django 3.2 on 2021-04-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0028_auto_20210428_1407'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calibratedparameter',
            name='waterspout__year_3ccc43_idx',
        ),
        migrations.RemoveIndex(
            model_name='inputdataitem',
            name='waterspout__year_56ef53_idx',
        ),
        migrations.RemoveIndex(
            model_name='rainfallparameter',
            name='waterspout__year_e37c47_idx',
        ),
        migrations.AlterUniqueTogether(
            name='calibratedparameter',
            unique_together={('crop', 'region', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='inputdataitem',
            unique_together={('crop', 'region', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='rainfallparameter',
            unique_together={('crop', 'region', 'year')},
        ),
    ]
