# Generated by Django 3.2 on 2021-04-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0029_auto_20210428_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='rainfall_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='waterspout_api.rainfallset'),
            preserve_default=False,
        ),
    ]
