# Generated by Django 3.2 on 2021-04-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0030_auto_20210429_1758'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calibratedparameter',
            name='waterspout__year_3ccc43_idx',
        ),
        migrations.RemoveIndex(
            model_name='inputdataitem',
            name='waterspout__year_56ef53_idx',
        ),
        migrations.RemoveIndex(
            model_name='rainfallparameter',
            name='waterspout__year_e37c47_idx',
        ),
        migrations.AlterField(
            model_name='regionmultipliers',
            name='direct_jobs',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regionmultipliers',
            name='direct_value_add',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regionmultipliers',
            name='total_jobs',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regionmultipliers',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='regionmultipliers',
            name='total_value_add',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
