# Generated by Django 3.2 on 2021-04-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0031_auto_20210430_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelrun',
            name='rainfall_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='waterspout_api.rainfallset'),
        ),
    ]
