# Generated by Django 3.2 on 2021-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0032_alter_modelrun_rainfall_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfallparameter',
            name='tspr',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rainfallparameter',
            name='tsum',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rainfallparameter',
            name='twin',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
