# Generated by Django 3.2 on 2021-04-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0034_auto_20210430_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rainfallresult',
            old_name='calc_y',
            new_name='calc_yield',
        ),
    ]
