# Generated by Django 3.2 on 2021-04-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0035_rename_calc_y_rainfallresult_calc_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfallresult',
            name='xlandsc',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rainfallresult',
            name='xwatersc',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
    ]
