# Generated by Django 3.2 on 2021-05-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0036_auto_20210430_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rainfallparameter',
            old_name='coef_pespr',
            new_name='coef_ptspr',
        ),
        migrations.RenameField(
            model_name='rainfallparameter',
            old_name='coef_pesum',
            new_name='coef_ptsum',
        ),
        migrations.RenameField(
            model_name='rainfallparameter',
            old_name='coef_pewin',
            new_name='coef_ptwin',
        ),
        migrations.RenameField(
            model_name='rainfallparameter',
            old_name='pespr',
            new_name='ptspr',
        ),
        migrations.RenameField(
            model_name='rainfallparameter',
            old_name='pesum',
            new_name='ptsum',
        ),
        migrations.RenameField(
            model_name='rainfallparameter',
            old_name='pewin',
            new_name='ptwin',
        ),
        migrations.AddField(
            model_name='rainfallparameter',
            name='coef_crop',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropmodification',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='waterspout_api.crop'),
        ),
        migrations.AlterField(
            model_name='cropmodification',
            name='crop_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='waterspout_api.cropgroup'),
        ),
        migrations.AlterField(
            model_name='cropmodification',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_modifications', to='waterspout_api.crop'),
        ),
        migrations.AlterField(
            model_name='modelrun',
            name='calibration_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_runs', to='waterspout_api.calibrationset'),
        ),
        migrations.AlterField(
            model_name='rainfallresult',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_results', to='waterspout_api.region'),
        ),
        migrations.AlterField(
            model_name='regionmodification',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='waterspout_api.region'),
        ),
        migrations.AlterField(
            model_name='regionmodification',
            name='region_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='waterspout_api.regiongroup'),
        ),
    ]
