# Generated by Django 3.2 on 2021-05-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0038_auto_20210505_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dense_tables',
            field=models.BooleanField(default=False),
        ),
    ]
