# Generated by Django 3.2 on 2021-06-14 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0039_userprofile_dense_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmodification',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_modifications', to='waterspout_api.region'),
        ),
        migrations.AlterUniqueTogether(
            name='cropmodification',
            unique_together={('model_run', 'crop', 'region')},
        ),
    ]
