# Generated by Django 3.2 on 2021-06-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0040_auto_20210613_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='default_behavior',
            field=models.SmallIntegerField(choices=[(0, 'Modeled'), (1, 'Removed'), (2, 'Fixed'), (3, 'Linear Scaled')],  default=0),
        ),
    ]
