# Generated by Django 3.2 on 2021-06-15 21:19

from django.db import migrations, models

def migrate_modeling_behaviors(apps, schema_editor):
    """
        Migrate from separate booleans to a single field with value choices - we'll then delete the other fields
    :param apps:
    :param schema_editor:
    :return:
    """
    RegionModifications = apps.get_model('waterspout_api', "RegionModification")

    for rm in RegionModifications.objects.all():
        if rm.removed == True:
            rm.modeled_type = 1  # specifying numbers because can't pull in the current number from the model registry
        if rm.hold_static == True:
            rm.modeled_type = 2

        rm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0041_region_default_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodification',
            name='modeled_type',
            field=models.SmallIntegerField(choices=[(0, 'Modeled'), (1, 'Removed'), (2, 'Fixed'), (3, 'Linear Scaled')], default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='default_behavior',
            field=models.SmallIntegerField(choices=[(0, 'Modeled'), (1, 'Removed'), (2, 'Fixed'), (3, 'Linear Scaled')], default=0),
        ),
        migrations.RunPython(migrate_modeling_behaviors),
        migrations.RemoveField(
            model_name='regionmodification',
            name='hold_static',
        ),
        migrations.RemoveField(
            model_name='regionmodification',
            name='removed',
        ),
    ]
