# Generated by Django 3.2 on 2021-06-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0043_fix_region_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='allow_linear_scaled_regions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='default_behavior',
            field=models.SmallIntegerField(choices=[(0, 'Modeled'), (1, 'Removed'), (2, 'Fixed'), (3, 'Linear Scaled')], default=0),
        ),
    ]
