# Generated by Django 3.2 on 2021-06-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0044_auto_20210616_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='use_default_region_behaviors',
            field=models.BooleanField(default=True),
        ),
    ]
