# Generated by Django 3.2 on 2021-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0045_modelareapreferences_use_default_region_behaviors'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='shared_model_runs',
            field=models.BooleanField(default=True),
        ),
    ]
