# Generated by Django 3.2.13 on 2022-05-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0047_auto_20220506_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='group',
        ),
        migrations.RemoveField(
            model_name='regiongroup',
            name='internal_id',
        ),
        migrations.AddField(
            model_name='regiongroup',
            name='regions',
            field=models.ManyToManyField(to='waterspout_api.Region'),
        ),
        migrations.AlterField(
            model_name='regiongroup',
            name='model_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_groups', to='waterspout_api.modelarea'),
        ),
    ]
