# Generated by Django 3.2.13 on 2022-05-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0048_auto_20220510_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiongroup',
            name='model_area',
        ),
        migrations.CreateModel(
            name='RegionGroupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_groups', to='waterspout_api.modelarea')),
            ],
        ),
        migrations.AddField(
            model_name='regiongroup',
            name='group_set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='waterspout_api.regiongroupset'),
            preserve_default=False,
        ),
    ]
