# Generated by Django 3.2.13 on 2022-05-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0049_auto_20220510_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='net_revenue_pmp_yield',
        ),
        migrations.RemoveField(
            model_name='result',
            name='net_revenue_red_costs',
        ),
        migrations.AddField(
            model_name='result',
            name='net_revenue_flag',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_net_revenues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regiongroupset',
            name='model_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_group_sets', to='waterspout_api.modelarea'),
        ),
    ]
