# Generated by Django 4.1.9 on 2023-11-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0055_load_dap_multipliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelareapreferences',
            name='create_or_modify_model_runs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='regiongroup',
            name='regions',
            field=models.ManyToManyField(related_name='groups', to='waterspout_api.region'),
        ),
    ]
