# Generated by Django 4.1.9 on 2023-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0056_modelareapreferences_create_model_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelarea',
            name='has_spatial_data',
            field=models.BooleanField(default=True),
        ),
    ]
