# Generated by Django 4.1.13 on 2024-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0058_alter_result_omegawater'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_map_popup',
            field=models.BooleanField(default=False),
        ),
    ]
