# Generated by Django 4.1.13 on 2025-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterspout_api', '0059_userprofile_show_map_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bulk_create',
            field=models.BooleanField(default=False),
        ),
    ]
