- hosts: webservers
  remote_user: nsantos5
  tasks:
    - name: Loading Configs
      include_vars: ansible-waterspout-variables.yml

    - name: Loading secrets
      include_vars: secrets.yml

    - name: Snap refresh
      become: true
      become_method: sudo
      shell: snap install core && snap refresh core

    - name: Remove certbot apt package, if it exists
      become: true
      become_method: sudo
      apt:
        name: certbot
        state: absent

    - name: Install Certbot from Snap
      become: true
      become_method: sudo
      community.general.snap:
        name: certbot
        classic: yes

    - name: Link Snap Certbot to usr/bin
      become: true
      become_method: sudo
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link

    - name: Enable HTTPS in nginx
      become: true
      become_method: sudo
      shell: "certbot --agree-tos -d {{ deploy_url }} --nginx -m {{ admin_address }}"

    - name: Test autorenewal
      become: true
      become_method: sudo
      shell: certbot renew --dry-run