---
- hosts: webservers
  remote_user: nsantos5
  tasks:
    - name: Loading variables
      include_vars: ansible-waterspout-variables.yml

    - name: Install Dapper system apt packages
      become: true
      become_method: sudo
      apt:
        update_cache: yes
        name: ['gcc','g++','gfortran','patch','wget','pkg-config','liblapack-dev','libmetis-dev','build-essential']
        state: present

    - name: Install GLPK Packages
      become: true
      become_method: sudo
      apt:
        update_cache: yes
        name: ['glpk-utils','libglpk-dev']
        state: present

    # install ipopt, but don't do it if ipopt_dist already exists
    - name: Compile and set up ipopt
      become: true
      become_method: sudo
      script:
        cmd: ipopt-build.sh
        creates: "{{ install_path }}/ipopt_dist"

    - name: Install Requests for when we retrieve Dapper
      pip:
        chdir: "{{ install_path }}"
        virtualenv: "{{ virtualenv_folder }}"
        name: requests

    - name: Get Dapper from S3
      command: "{{ virtualenv_python_executable}} {{ back_end_application_folder }}/utils/get_dapper.py"