# This file is for running tests that don't actually execute Dapper (so we don't need to install Dapper dependencies)

name: Run NonDapper Tests

on:
  push:
    branches: [ development, release ]
  pull_request:
    branches: [ development, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Dapper from S3
      run: |
        python -m pip install requests
        python utils/get_dapper.py
    - name: Test with pytest
      run: |
        python manage.py test
